### ISSUE TITLE
Game Tutorial

### ISSUE THREAD

**Issue by adamhannigan** [sunflower-land/sunflower-land#140]
Similar to Sunflower Farmers, introduce an in game tutorial which onboards users. It should give them a quick run down of the map and how the game works.

### Tasks

- [ ] Harvest a sunflower (# pr no. resolving this task)
- [ ] Inventory
- [ ] Sell a sunflower
- [ ] Buy a sunflower
- [ ] Plant a seed
- [ ] Crafting -> Tools, Rare Items, Food
- [ ] Saving
- [ ] Sync on Chain
- [ ] Withdraw

**Comment by Pranav-yadav** [comment]
Hey @adamhannigan, I would suggest to create milestones for **enhancements** and **arts** and also for new *features**. So that, issues can be tracked in a better way. 👍

**Comment by adamhannigan** [comment]
@Pranav-yadav Good suggestion.

Can you provide some examples of milestones you think would make sense for the project?

**Comment by Pranav-yadav** [comment]
E.g. We can create milestones for, 
### Mobile Support 📱
- Which will consist all issues & PR's related to adding complete mobile support in the game.

### Community Crafting 👥
- all issues & PR's related to adding community crafting features in the game.

### Buy & Sell Whole Farm/ Swapping 💰💱
- all issues & PR's related to adding this feature in the game.


### Tests 🧪
- all issues & PR's related to adding tests.

Or simply milestones from **roadmap**
> Or you can even opt for projects beta which requires some setup (projects)

Also, one more suggestion please try to use, **issue tasks list** (on github we can create tasks inside an issue) (check) instead of bullets for todo's. E.g.
> - [ ] Harvest Sunflower Tut

👍

**Comment by Pranav-yadav** [comment]
<details><summary>E.g.: Screenshots for ref.</summary>
<img src="https://user-images.githubusercontent.com/55224033/150628497-8652ff66-ddc3-483b-aa22-e14f17af63fd.jpg" />
<img src="https://user-images.githubusercontent.com/55224033/150628500-9cdc0f14-b93c-4130-b816-99078eff1c5b.jpg" />
</details>

**Comment by adamhannigan** [comment]
@Pranav-yadav Thanks for the detailed response. That is very clear.

I will set this up over the coming days.
